Add basic Github CI test
Meteor-Community-Packages/meteor-user-status pull request #186
Opened 2024-06-20 12:37 UTC by harryadel

A basic CI to replace travis

2024-06-20 15:43 UTC, StorytellerCZ requested changes

2024-06-20 15:43 UTC, StorytellerCZ commented on .github/workflows/testsuite.yml
> +          node-version: "12.x"
Should be 14

2024-06-20 16:02 UTC, harryadel commented on .github/workflows/testsuite.yml
> +          node-version: "12.x"
Done!

2024-06-21 07:41 UTC, StorytellerCZ approved these changes

2024-06-21 07:41 UTC, merged